mode: mcts
question: null
golden_answer: null
num_proc: 8
results_dir: results/mcts/depth_5
to_eval_path: null
search:
  max_depth: 5
  top_k: 3
  num_rollouts: 10
  use_golden_answer: false
  save_tree: true
  exploration_weight: 1.0
  verbose: false
  tree_dir: mcts_trees
data:
  name: bamboogle
  split: null
  limit: 1000
  metrics:
  - llm_judge
  - sub_em
agents:
  generator:
    name: generator
    client_kwargs:
      model_name: Qwen/Qwen3-8B
      url: http://n0999:8000/v1
      api_key: Your-API-Key-Here
      client_type: openai
      concurrency: 64
    generation_config:
      temperature: 1.0
      'n': 1
      top_p: 0.9
      max_tokens: 4096
      top_k: 20
    use_cache: true
    cache_dir: cache/generator
    enable_global_rate_limit: true
    num_workers: 32
    rate_limit: 256
    timeout: 1000
  evaluator:
    name: evaluator
    client_kwargs:
      model_name: Qwen/Qwen3-8B
      url: http://n0999:8000/v1
      api_key: Your-API-Key-Here
      client_type: openai
      concurrency: 64
    generation_config:
      temperature: 0.1
      'n': 3
      top_p: 0.9
      max_tokens: 4096
      top_k: 20
    use_cache: true
    cache_dir: cache/evaluator
    enable_global_rate_limit: true
    num_workers: 32
    rate_limit: 32
    timeout: 1000
  extractor:
    name: extractor
    client_kwargs:
      model_name: Hieuman/State-Aware-RAG-Extractor-4B.v0
      url: http://localhost:30000/v1
      api_key: Your-API-Key-Here
      client_type: openai
      concurrency: 64
    generation_config:
      temperature: 0.1
      'n': 3
      top_p: 0.9
      max_tokens: 4096
      top_k: 20
    use_cache: true
    cache_dir: cache/extractor
    enable_global_rate_limit: true
    num_workers: 32
    rate_limit: 256
    timeout: 1000
  retriever:
    name: retriever
    online_retrieval_config:
      url: http://n0998:5000/search
      query_instruction: null
    top_k: 5
    enable_global_rate_limit: true
    num_workers: 32
    rate_limit: 256
    timeout: 1000
  evaluator_metric:
    name: evaluator-metric
    client_kwargs:
      model_name: Qwen/Qwen2.5-72B-Instruct
      url: http://n0998:30000/v1
      api_key: Your-API-Key-Here
      client_type: openai
      concurrency: 64
    generation_config:
      temperature: 0.1
      'n': 3
      top_p: 0.9
      max_tokens: 4096
      top_k: 20
    use_cache: false
    cache_dir: "cache/evaluator-metric"
    enable_global_rate_limit: true
    num_workers: 16
    rate_limit: 16
    timeout: 1000
