# You must make sure that the model and the index are compatible.
encoder_model_base_url: http://ip-10-4-226-141:8000/v1
encoder_model_api_key: YOUR_OPENAI_API_KEY
# Path settings
corpus_path: data/wiki18_100w.jsonl
index_path: data/e5_flat_inner.index
