name: extractor
client_kwargs:
  model_name: "openai/qwen3-8B"
  url: "http://ip-10-4-230-228:30000/v1"
  api_key: "Your-API-Key-Here"
  client_type: "openai"
  concurrency: 64
# client_kwargs:
#   model_name: "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
#   # 'model_name': 'bedrock/us.deepseek.r1-v1:0'  # Use DeepSeek R1 model
#   url: null  # Use default URL for the model
#   api_key: null  # Set your API key if required
#   aws_profile_name: "hieu" # 'aws_profile_name': 'hieu',  # Set your AWS profile name if using AWS Bedrock
#   client_type: "litellm"
#   concurrency: 64

generation_config:
  temperature: 0.1
  n: 3
  top_p: 0.9
  max_tokens: 4096
  top_k: 20

use_cache: true
cache_dir: "cache/extractor"
enable_global_rate_limit: false
num_workers: 128
rate_limit: 256
timeout: 500
