name: generator
client_kwargs:
  model_name: "openai/qwen3-8B"
  url: "http://ip-10-4-230-228:30000/v1"
  api_key: "Your-API-Key-Here"
  client_type: "openai"
  concurrency: 64

generation_config:
  temperature: 1.0
  n: 1
  top_p: 0.9
  max_tokens: 4096
  top_k: 20

use_cache: true
cache_dir: "cache/generator"
enable_global_rate_limit: false
num_workers: 128
rate_limit: 256
timeout: 500