- name: state_aware
  _target_: recipe.state_aware.stage_aware_loop.StageAwareLoop
  retrieval_config_path: /fsx/ubuntu/users/hieuman/state-aware-rag/configs/retriever.yaml
  generator_config_path: /fsx/ubuntu/users/hieuman/state-aware-rag/configs/generator.yaml
  evaluator_config_path: /fsx/ubuntu/users/hieuman/state-aware-rag/configs/evaluator.yaml
  max_iterations: 5
  verbose: true
  